name: example
description: A new Flutter project.
publish_to: "none" 
version: 2.0.0

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_beacon: ^0.5.1
  get: ^4.6.5

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.15

  permission_handler: ^10.4.3
  bluetooth_enable_fork: ^0.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true